name: PetMaster
main: com.hm.petmaster.PetMaster
version: ${project.version}
author: DarkPyves
softdepend: [HolographicDisplays, Vault]
load: POSTWORLD
description: Whose pet is this? Manage pets and display information via holograms, action bar or chat messages!
website: https://github.com/PyvesB/PetMaster
api-version: 1.13
commands:
  petm:
    description: Main Pet Master command, use it to list sub-commands. 
    aliases: [petmaster]  
    usage: /<command>
permissions:
  petmaster.showowner:
    description: Allows players to see who owns pets that belong to other players. If false, the more specialised showowner permissions will be ignored.
    default: true
  petmaster.showowner.dog:
    description: Allows players to see who owns dogs that belong to other players.
    default: true
  petmaster.showowner.cat:
    description: Allows players to see who owns cats that belong to other players.
    default: true
  petmaster.showowner.horse:
    description: Allows players to see who owns horses that belong to other players.
    default: true
  petmaster.showowner.llama:
    description: Allows players to see who owns llamas that belong to other players.
    default: true
  petmaster.showowner.parrot:
    description: Allows players to see who owns parrots that belong to other players.
    default: true
  petmaster.setowner:
    description: Allows players to change the ownership of their own pets.
    default: true
  petmaster.setcolor:
    description: Allows players to change the default collar color of their newly tamed pets.
    default: true
  petmaster.free:
    description: Allows players to free their own pets.
    default: true
  petmaster.admin:
    description: Allows to enable/disable/reload the plugin, change the ownership/free pets of other players for free, get notified by updates.
    default: op
  petmaster.*:
    description: Star notation of permissions, includes all of them.
    default: op
    children:
      petmaster.admin: true
      petmaster.setowner: true
    
